#EJEMPLO CADENA CON DECIMALES
s = "1.23,2.4,3.123"

#SE USA LA FUNCION EVAL() PARA CREAR UNA LISTA CON LOS NUMEROS QUE TENGA LA CADENA 
#ANTERIOR
#EL LINK DONDE SAQUE LA IDEA ES CITADO EN EL ENUNCIADO
l=eval(s)
#PARA SUMAR TODOS LOS ELEMENTOS EN UNA LISTA, SE USA SUM()
print 'La suma de todos los numeros es', sum(l)