	#PROGRAMA RAIZ

	#COMENZAR CON g = 1 

g = 1

	#SOLICITAR AL USUARIO UN VALOR FLOTANTE

x = float(input('Ingresa un valor = '))

	#MIENTRAS QUE LA SIGUIENTE EXPRESION SEA MAYOR A 0.01
	#MIENTRAS MAS PEQUENO SEA EL MIEMBRO DERECHO MAS PRECISO ES EL RESULTADO
while abs((g*g)/x-1.)>0.01:
	#g IRA ADQUIRIENDO NUEVOS VALORES
	g=(g+x/g)/2

	#SI LA EXPRESION ANTERIOR ES MENOR AL VALOR ESTABLECIDO ANTES
	#IMPRIMIR g
if abs((g*g)/x-1.)<0.01:
	print ('La raiz de '+str(x)+' es '+str(g))


